/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as NegocioRouteImport } from './routes/negocio'
import { Route as ParticipantesRouteImport } from './routes/participantes'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as PerfilIdRouteImport } from './routes/perfil.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const NegocioRoute = NegocioRouteImport.update({
  id: '/negocio',
  path: '/negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantesRoute = ParticipantesRouteImport.update({
  id: '/participantes',
  path: '/participantes',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilIdRoute = PerfilIdRouteImport.update({
  id: '/perfil/$id',
  path: '/perfil/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/negocio': typeof NegocioRoute
  '/participantes': typeof ParticipantesRoute
  '/ranking': typeof RankingRoute
  '/perfil/$id': typeof PerfilIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/negocio': typeof NegocioRoute
  '/participantes': typeof ParticipantesRoute
  '/ranking': typeof RankingRoute
  '/perfil/$id': typeof PerfilIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favoritos': typeof FavoritosRoute
  '/negocio': typeof NegocioRoute
  '/participantes': typeof ParticipantesRoute
  '/ranking': typeof RankingRoute
  '/perfil/$id': typeof PerfilIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favoritos'
    | '/negocio'
    | '/participantes'
    | '/ranking'
    | '/perfil/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favoritos'
    | '/negocio'
    | '/participantes'
    | '/ranking'
    | '/perfil/$id'
  id:
    | '__root__'
    | '/'
    | '/favoritos'
    | '/negocio'
    | '/participantes'
    | '/ranking'
    | '/perfil/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritosRoute: typeof FavoritosRoute
  NegocioRoute: typeof NegocioRoute
  ParticipantesRoute: typeof ParticipantesRoute
  RankingRoute: typeof RankingRoute
  PerfilIdRoute: typeof PerfilIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/negocio': {
      id: '/negocio'
      path: '/negocio'
      fullPath: '/negocio'
      preLoaderRoute: typeof NegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participantes': {
      id: '/participantes'
      path: '/participantes'
      fullPath: '/participantes'
      preLoaderRoute: typeof ParticipantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$id': {
      id: '/perfil/$id'
      path: '/perfil/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof PerfilIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritosRoute: FavoritosRoute,
  NegocioRoute: NegocioRoute,
  ParticipantesRoute: ParticipantesRoute,
  RankingRoute: RankingRoute,
  PerfilIdRoute: PerfilIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
