/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedFavoritosRouteImport } from './routes/_authenticated/favoritos'
import { Route as AuthenticatedNegocioRouteImport } from './routes/_authenticated/negocio'
import { Route as AuthenticatedParticipantesRouteImport } from './routes/_authenticated/participantes'
import { Route as AuthenticatedRankingRouteImport } from './routes/_authenticated/ranking'
import { Route as AuthenticatedPerfilIdRouteImport } from './routes/_authenticated/perfil.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritosRoute = AuthenticatedFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNegocioRoute = AuthenticatedNegocioRouteImport.update({
  id: '/negocio',
  path: '/negocio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedParticipantesRoute =
  AuthenticatedParticipantesRouteImport.update({
    id: '/participantes',
    path: '/participantes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRankingRoute = AuthenticatedRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilIdRoute = AuthenticatedPerfilIdRouteImport.update({
  id: '/perfil/$id',
  path: '/perfil/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/negocio': typeof AuthenticatedNegocioRoute
  '/participantes': typeof AuthenticatedParticipantesRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/perfil/$id': typeof AuthenticatedPerfilIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/favoritos': typeof AuthenticatedFavoritosRoute
  '/negocio': typeof AuthenticatedNegocioRoute
  '/participantes': typeof AuthenticatedParticipantesRoute
  '/ranking': typeof AuthenticatedRankingRoute
  '/': typeof AuthenticatedIndexRoute
  '/perfil/$id': typeof AuthenticatedPerfilIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/favoritos': typeof AuthenticatedFavoritosRoute
  '/_authenticated/negocio': typeof AuthenticatedNegocioRoute
  '/_authenticated/participantes': typeof AuthenticatedParticipantesRoute
  '/_authenticated/ranking': typeof AuthenticatedRankingRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/perfil/$id': typeof AuthenticatedPerfilIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/favoritos'
    | '/negocio'
    | '/participantes'
    | '/ranking'
    | '/perfil/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/favoritos'
    | '/negocio'
    | '/participantes'
    | '/ranking'
    | '/'
    | '/perfil/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/favoritos'
    | '/_authenticated/negocio'
    | '/_authenticated/participantes'
    | '/_authenticated/ranking'
    | '/_authenticated/'
    | '/_authenticated/perfil/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favoritos': {
      id: '/_authenticated/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AuthenticatedFavoritosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/negocio': {
      id: '/_authenticated/negocio'
      path: '/negocio'
      fullPath: '/negocio'
      preLoaderRoute: typeof AuthenticatedNegocioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/participantes': {
      id: '/_authenticated/participantes'
      path: '/participantes'
      fullPath: '/participantes'
      preLoaderRoute: typeof AuthenticatedParticipantesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ranking': {
      id: '/_authenticated/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AuthenticatedRankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil/$id': {
      id: '/_authenticated/perfil/$id'
      path: '/perfil/$id'
      fullPath: '/perfil/$id'
      preLoaderRoute: typeof AuthenticatedPerfilIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedFavoritosRoute: typeof AuthenticatedFavoritosRoute
  AuthenticatedNegocioRoute: typeof AuthenticatedNegocioRoute
  AuthenticatedParticipantesRoute: typeof AuthenticatedParticipantesRoute
  AuthenticatedRankingRoute: typeof AuthenticatedRankingRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPerfilIdRoute: typeof AuthenticatedPerfilIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedFavoritosRoute: AuthenticatedFavoritosRoute,
  AuthenticatedNegocioRoute: AuthenticatedNegocioRoute,
  AuthenticatedParticipantesRoute: AuthenticatedParticipantesRoute,
  AuthenticatedRankingRoute: AuthenticatedRankingRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPerfilIdRoute: AuthenticatedPerfilIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
